### ISSUE TITLE
是否有打包好的maven jar 提供呢

### ISSUE THREAD

**Issue by rjzou** [wuba/WPaxos#1]
1. 是否有打包好的maven jar 提供呢？
2. 在生产环境上使用的稳定吗？

**Comment by liuliuwd** [comment]
maven中央仓库的WPaxos jar包有计划在下周发布；
WPaxos在生产环境中运行稳定，针对一些网络分区、进程异常（OOM、强制关闭）等突发情况，已经过一系列实际应用场景的验证。
