### ISSUE TITLE
phxpaxos 只用32G 内存测试服务器做测试？

### ISSUE THREAD

**Issue by rjzou** [wuba/WPaxos#2]
测试结果表明，是否在基础架构方面java 的性能确实跟不上c++呢？

**Comment by liuliuwd** [comment]
从测试结果看，Java版的WPaxos相对于C++版本整体性能上没有明显落后，WPaxos在网络IO模型、批量化提交、索引方式等方面有些改造，测试结果不能完全同等对比。另外，整体性能瓶颈不在内存，所以32G内存和192G内存对性能影响不大。
