### ISSUE TITLE
NULL defeference

### ISSUE THREAD

**Issue by hailinzeng** [wuba/WPaxos#3]
https://github.com/wuba/WPaxos/blob/8d7389e4ced4e6ecdf7d080e2f678a5163f0aaa1/core/src/main/java/com/wuba/wpaxos/store/DefaultDataBase.java#L253-L256

pdr

**Comment by liuliuwd** [comment]
感谢 @hailinzeng，如果pdr为空，此处确实会有空指针，虽然当前代码中pdr都有赋值不会为空，还是单独再加上判断比较好
